In [47]:
import pandas as pd
import numpy as np
from scipy import stats

### Задача 1 
Даны значения величины заработной платы заемщиков банка (zp) и значения их
поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с
помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и
среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [14]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
cov = np.mean(zp * ks) - np.mean(zp) * np.mean(ks)
cov

9157.839999999997

In [15]:
np.cov(zp, ks, ddof = 0) # смещенная ковариация

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [16]:
np.cov(zp, ks, ddof = 1) # несмещенная ковариация

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [19]:
sigmazp = np.std(zp, ddof = 0)
sigmazp

59.115480206118605

In [20]:
sigmaks = np.std(ks, ddof = 0)
sigmaks

174.55340157098058

In [21]:
corpirs = cov/(sigmazp * sigmaks)
corpirs

0.8874900920739158

In [23]:
sigmazp1 = np.std(zp, ddof = 1)
sigmazp1

62.31318747531162

In [24]:
sigmaks1 = np.std(ks, ddof = 1)
sigmaks1

183.99544076477068

In [25]:
corpirs1 = 10175.37777778/(sigmazp1 * sigmaks1)
corpirs1

0.88749009207411

In [27]:
np.corrcoef(zp, ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

### Задача 2 
Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [30]:
IQ = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
alpha = 0.05

Необходимо найти доверительный интервал для средних арифметических, а так как сигма генеральной совокупности нам неизвестна, то используем формулу: M +- t(alpha/2) * sigma/sqrt(n) 

In [32]:
M = IQ.mean()
M

118.1

In [33]:
sigma = np.std(IQ, ddof = 1)
sigma

10.54566788359614

In [34]:
n = 10

In [35]:
t = stats.t.ppf(0.975, 9)
t

2.2621571627409915

In [36]:
M - t * sigma/np.sqrt(n)

110.55608365158724

In [37]:
M + t * sigma/np.sqrt(n)

125.64391634841274

In [44]:
print(f'Доверительный интервал для математического ожидания: ({M - t * sigma/np.sqrt(n):.2f} ; {M + t * sigma/np.sqrt(n):.2f})')

Доверительный интервал для математического ожидания: (110.56 ; 125.64)


### Задача 3 
Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для
математического
ожидания с надежностью 0.95.

In [45]:
alpha = 0.05
var = 25
n = 27
M = 174.2

Необходимо найти доверительный интервал для средних арифметических, а так как сигма генеральной совокупности нам известна, то используем формулу: M +- z(alpha/2) * sigma/sqrt(n) 

In [50]:
z = stats.norm.ppf(alpha/2)
z

-1.9599639845400545

In [51]:
M - z * np.sqrt(var/n)

176.08597622346028

In [52]:
M + z * np.sqrt(var/n)

172.3140237765397

In [53]:
print(f'Доверительный интервал для средних арифметических: ({M + z * np.sqrt(var/n):.2f} ; {M - z * np.sqrt(var/n):.2f})')

Доверительный интервал для средних арифметических: (172.31 ; 176.09)
